version: "3"
services: 

  es:
    image: elasticsearch:7.5.1
    networks:
      eslastic_nw:
        aliases:
          - esdb
    ports: 
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./data:/usr/share/elasticsearch/data

  kb:
    image: kibana:7.5.1
    networks:
      - eslastic_nw
    links:
      - es
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200

networks:
  eslastic_nw: