PUT http://localhost:9200/_bulk?pretty HTTP/1.1
Content-Type: application/json

{ "create": { "_id": "8852429309002", "_index": "products" } }
{ "SAP_Product_ID": "ZDA300300010025005", "Barcode": "8852429309002", "CMS_ID": "113109", "Name": "ปูนกาวยิปซัม อีซี่บอนด์ ตราช้าง", "Brand": "ยิปซัมตราช้าง", "Short_Description": "ปูนกาวยิปซัม อีซี่บอนด์ ใช้สำหรับติดตั้งร่วมกับแผ่นยิปซัมเพื่อติดทับผนังเดิม (Easy Finish) เพื่อเพิ่มคุณสมบัติให้ผนังมีความเป็นฉนวนกันความร้อนและป้องกันเสียงลดกวนได้ดีขึ้น และยังสามารถใช้เป็นระบบปิดผิวผนังเดิมให้ดูเรียบเนียน ไม่แตกร้าว แทนการฉาบปูนบนผนังทั้งผื่น ติดแน่นทนทานยึดเกาะดีเยี่ยม สูตรเฉพาะสำหรับติดแผ่นยิปซัม เนื้อปูนละเอียด ผสมง่าย ปูนแห้งไว ประหยัดเวลา ติดตั้งง่าย ใช้ได้กับทั้งผนังก่ออิฐและผนังคอนกรีตสำเร็จ", "Active_Status_Website": "Yes", "Is_Out_Of_Stock": "false", "Language": "TH", "Market": "THA", "Main_Image": "https://dev-dam-products.storage.googleapis.com/product%2F113109%2Fimages%2Fb056c314-5b65-4cbb-9fd9-3259ccc4c370%2FCompound-Easy%20Bond.jpg", "Modified": "2019-08-13T10:20:00.000Z", "Category_Name": [ "วัสดุตกแต่ง และปิดผิว" ], "Subcategory_Name": [ "แผ่นยิปซั่มบอร์ด" ] }
{ "create": { "_id": "2322004750018", "_index": "products" } }
{ "SAP_Product_ID": "2322004750018", "Barcode": "2322004750018", "CMS_ID": "191640", "Name": "BISON มอเตอร์เครื่องจี้ปูน ZX50-A น้ำเงิน", "Brand": "BISON", "Short_Description": "• ตัวเครื่องมีประสิทธิภาพที่ดีเยี่ยม มีอายุการใช้งานที่ยาวนาน• ความถี่และการสั่นสะเทือนสูง • สายผลิตจากยางคุณภาพดี• หัวจี้ผลิตจากเหล็กหล่อป้องกันสนิมป้องกันการกัดกร่อน • ทนแรงกระแทรก น้ำหนักเบา กะทัดรัด สะดวกและง่ายต่อการใช้งาน", "Active_Status_Website": "Yes", "Is_Out_Of_Stock": "false", "Language": "TH", "Market": "THA", "Main_Image": "https://dev-dam-products.storage.googleapis.com/product%2F191640%2Fimages%2Fbac8989e-4e60-43d9-8fc0-ba452f560f6e%2F2322004750018.jpg", "Modified": "2019-05-14T12:12:00.000Z", "Category_Name": [ "เครื่องมือช่าง ฮาร์ดแวร์ และ DIY" ], "Subcategory_Name": [ "เครื่องมือช่าง" ]}
{ "create": { "_id": "8852853014664", "_index": "products" } }
{ "SAP_Product_ID": "ZCESS009300A000", "Barcode": "8852853014664", "CMS_ID": "4494", "Name": "ปูนประสานร่อง เอสซีจี 50 กก. สีครีม", "Brand": "เอสซีจี", "Short_Description": "เสริมความแข็งแกร่งให้กับพื้นบล็อก", "Active_Status_Website": "Yes", "Is_Out_Of_Stock": "false", "Language": "TH", "Market": "THA", "Main_Image": "https://dev-dam-products.storage.googleapis.com/product%2F4494%2Fimages%2F455a6934-f09c-4164-93d3-f6fc01a55397%2Fprd-8852853014664-high1_pd24776.jpg", "Modified": "2018-01-07T04:51:00.000Z", "Category_Name": [ "วัสดุตกแต่ง และปิดผิว" ], "Subcategory_Name": [ "บล็อกปูพื้น กระเบื้องคอนกรีต รั้วและอุปกรณ์ตกแต่งสวน" ]}
{ "create": { "_id": "8852853014640", "_index": "products" } }
{ "SAP_Product_ID": "ZCESS009300I000", "Barcode": "8852853014640", "CMS_ID": "4490", "Name": "ปูนประสานร่อง เอสซีจี 50 กก. สีดำ", "Brand": "เอสซีจี", "Short_Description": "เสริมความแข็งแกร่งให้กับพื้นบล็อก", "Active_Status_Website": "Yes", "Is_Out_Of_Stock": "false", "Language": "TH", "Market": "THA", "Main_Image": "https://dev-dam-products.storage.googleapis.com/product%2F4490%2Fimages%2F675784c6-1200-48c7-9767-c2980e5979b3%2Fcpac%20design_jointing%20cement_big_high_pd24754.jpg", "Modified": "2018-01-07T04:51:00.000Z", "Category_Name": [ "วัสดุตกแต่ง และปิดผิว" ], "Subcategory_Name": [ "บล็อกปูพื้น กระเบื้องคอนกรีต รั้วและอุปกรณ์ตกแต่งสวน" ]}
{ "create": { "_id": "8852429307961", "_index": "products" } }
{ "SAP_Product_ID": "ZDA300100060025005", "Barcode": "8852429307961", "CMS_ID": "16296", "Name": "ปูนฉาบรอยต่อ อีซี่พลาส 120 ตราช้าง", "Brand": "ยิปซัมตราช้าง", "Short_Description": "ปูนฉาบรอยต่อ อีซี่พลาส120 ตราช้าง เหมาะสำหรับงานฉาบรอยต่อแผ่นยิปซัม ฉาบเก็บรอยหัวสกรู เนื้อปูนละเอียด สูตรแห้งช้า สำหรับหน้างานใหญ่สามารถทำงานได้นานขึ้น ผสมเข้ากับน้ำง่าย ฉาบลื่นเบาแรง  แรงยึดเกาะสูง ผิวเนียนละเอียด ขัดตกแต่งง่าย ทาสีทับง่ายไม่หลุดร่อน", "Active_Status_Website": "Yes", "Is_Out_Of_Stock": "false", "Language": "TH", "Market": "THA", "Main_Image": "https://dev-dam-products.storage.googleapis.com/product%2F16296%2Fimages%2Fc8898fc4-1f0e-4cd9-b9e5-848f5251504a%2FEasy%20Plas%20120.jpg", "Modified": "2019-11-03T17:04:00.000Z", "Category_Name": [ "วัสดุตกแต่ง และปิดผิว" ], "Subcategory_Name": [ "แผ่นยิปซั่มบอร์ด" ]}
{ "create": { "_id": "8852429310077", "_index": "products" } }
{ "SAP_Product_ID": "ZDA300100060025010", "Barcode": "8852429310077", "CMS_ID": "113107", "Name": "ปูนฉาบรอยต่อ อีซี่ควิก ตราช้าง", "Brand": "ยิปซัมตราช้าง", "Short_Description": "ปูนฉาบรอยต่อ อีซีควิก ตราช้าง สูตรใหม่พิเศษฉาบทับได้ไวขึ้นไม่ต้องรอนาน สำหรับงานฉาบรอยต่อแผ่นยิปซัม ฉาบรอยต่อหัวตะปู และฉาบตกแต่งพื้นผิวหน้ายิปซัม เฉพาะภายใน ระยะเวลาทำงาน 75 นาที ผสมง่าย ฉาบลื่น ยึดเกาะสูง ไม่แตกร้าว", "Active_Status_Website": "Yes", "Is_Out_Of_Stock": "false", "Language": "TH", "Market": "THA", "Main_Image": "https://dev-dam-products.storage.googleapis.com/product%2F113107%2Fimages%2F101db2f3-45b4-442e-a897-31b8a29f15c9%2Feasy-quik_pd403189.jpg", "Modified": "2019-08-13T10:20:00.000Z", "Category_Name": [ "วัสดุตกแต่ง และปิดผิว" ], "Subcategory_Name": [ "แผ่นยิปซั่มบอร์ด" ]}
{ "create": { "_id": "8852437100189", "_index": "products" } }
{ "SAP_Product_ID": "ZBAB12102D50K3", "Barcode": "8852437100189", "CMS_ID": "1348", "Name": "ปูนงานโครงสร้าง เอสซีจี (ปูนซีเมนต์ถุง 50 กก.)", "Brand": "เอสซีจี", "Short_Description": "ปูนซีเมนต์ปอร์ตแลนด์ประเภท 1 มีคุณสมบัติให้กำลังอัดสูง เหมาะสำหรับงานโครงสร้างที่ต้องการความแข็งแรงสูง อาทิ ฐานราก เสา คาน พื้น ของบ้านพักอาศัย อาคารทั่วไป และงานโครงสร้างขนาดใหญ่ อาทิ อาคารสูง ถนน ทางด่วน สนามกีฬา และสนามบิน โครงสร้างที่ได้มีความแข็งแรง ทนทาน", "Active_Status_Website": "Yes", "Is_Out_Of_Stock": "false", "Language": "TH", "Market": "THA", "Main_Image": "https://dev-dam-products.storage.googleapis.com/product%2F1348%2Fimages%2F163fce85-d8f3-40d5-ab58-0a32086f42b0%2F8852437100189_scg%20portland%20cement%20type%201_pd366039.jpg", "Modified": "2018-06-05T09:58:00.000Z",  "Category_Name": [ "งานโครงสร้าง"] }
{ "create": { "_id": "8852853014657", "_index": "products" } }
{ "SAP_Product_ID": "ZCESS009300C000", "Barcode": "8852853014657", "CMS_ID": "4492", "Name": "ปูนประสานร่อง เอสซีจี 50 กก. สีน้ำตาล", "Brand": "เอสซีจี", "Short_Description": "เสริมความแข็งแกร่งให้กับพื้นบล็อก", "Active_Status_Website": "Yes", "Is_Out_Of_Stock": "false", "Language": "TH", "Market": "THA", "Main_Image": "https://dev-dam-products.storage.googleapis.com/product%2F4492%2Fimages%2Fc5a9edd9-b0ac-4d5a-8d56-e35b6eba8975%2Fprd-8852853014657-high1_pd24765.jpg", "Modified": "2018-01-07T04:52:00.000Z", "Category_Name": [ "วัสดุตกแต่ง และปิดผิว" ], "Subcategory_Name": [ "บล็อกปูพื้น กระเบื้องคอนกรีต รั้วและอุปกรณ์ตกแต่งสวน" ]}