POST http://localhost:9200/products/_search HTTP/1.1
Content-Type: application/json

{
   "from": "0",
   "size": "50",
   "query": {
      "multi_match": {
        "query": "200",
        "fields": [
          "Barcode"
        ]
      }
   }
}